import { observable, action, configure } from 'mobx';
import * as r from 'ramda';
import Store from 'electron-store';

import x from 'x';
import * as settings from 'js/settings';

const store = new Store();
configure({ enforceActions: 'observed' });

//--

const { color_input_default } = settings.ob.theme_vals[store.get('theme')];

export const reset_inputs_data = action(() => {
    try {
        inputs_data.obj = data_obj_default;

        settings.load_setting();

    } catch (er) {
        err(er, 45);
    }
});

export const inputs_data = observable({
    obj: {
        theme_metadata: [
            {
                key: x.unique_id(),
                name: 'version',
                family: 'theme_metadata',
                type: 'textarea',
                val: '',
            },
            {
                key: x.unique_id(),
                name: 'icon',
                family: 'theme_metadata',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'locale',
                family: 'theme_metadata',
                type: 'select',
                val: '',
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'name',
                family: 'theme_metadata',
                type: 'textarea',
                val: '',
                add_help: true,
                counter: true,
                char_limit: 45,
            },
            {
                key: x.unique_id(),
                name: 'description',
                family: 'theme_metadata',
                type: 'textarea',
                val: '',
                add_help: true,
                counter: true,
                char_limit: 132,
            },
            {
                key: x.unique_id(),
                name: 'default_locale',
                family: 'theme_metadata',
                type: 'select',
                val: '',
                add_help: true,
            },
        ],
        images: [
            {
                key: x.unique_id(),
                name: 'theme_ntp_background',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_toolbar',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_frame',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_frame_inactive',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_frame_incognito',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_frame_incognito_inactive',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_frame_overlay',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_frame_overlay_inactive',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_tab_background',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_tab_background_incognito',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_window_control_background',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                color: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'theme_ntp_attribution',
                family: 'images',
                type: 'img_selector',
                val: '',
                highlight_upload_box: false,
                default: true,
                add_help: true,
            },
        ],
        colors: [
            {
                key: x.unique_id(),
                name: 'ntp_background',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'toolbar',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame_inactive',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame_incognito',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame_incognito_inactive',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'bookmark_text',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'tab_text',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'tab_background_text',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'button_background',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'ntp_text',
                family: 'colors',
                type: 'color',
                val: color_input_default,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
        ],
        tints: [
            {
                key: x.unique_id(),
                name: 'frame',
                family: 'tints',
                type: 'color',
                val: color_input_default,
                disabled: false,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame_inactive',
                family: 'tints',
                type: 'color',
                val: color_input_default,
                disabled: false,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame_incognito',
                family: 'tints',
                type: 'color',
                val: color_input_default,
                disabled: false,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'frame_incognito_inactive',
                family: 'tints',
                type: 'color',
                val: color_input_default,
                disabled: false,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'background_tab',
                family: 'tints',
                type: 'color',
                val: color_input_default,
                disabled: false,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'buttons',
                family: 'tints',
                type: 'color',
                val: color_input_default,
                disabled: false,
                color_pickier_is_visible: false,
                color_pickiers_position: 'top',
                default: true,
                add_help: true,
            },
        ],
        properties: [
            {
                key: x.unique_id(),
                name: 'ntp_background_alignment',
                family: 'properties',
                type: 'select',
                val: '',
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'ntp_background_repeat',
                family: 'properties',
                type: 'select',
                val: '',
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'ntp_logo_alternate',
                family: 'properties',
                type: 'select',
                val: '',
                add_help: true,
            },
        ],
        settings: [
            {
                key: x.unique_id(),
                name: 'theme',
                family: 'settings',
                type: 'select',
                val: '',
            },
            {
                key: x.unique_id(),
                name: 'chrome_exe_path',
                family: 'settings',
                type: 'textarea',
                val: '',
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'chrome_user_data_dirs',
                family: 'settings',
                type: 'textarea',
                val: '',
                add_help: true,
            },
            {
                key: x.unique_id(),
                name: 'enable_analytics',
                family: 'settings',
                type: 'checkbox',
                val: true,
                add_help: false,
                hidden: true,
            },
        ],
    },
});

const data_obj_default = r.clone(inputs_data.obj);

observable(inputs_data);
